version: '3'

networks:
  default:
    driver: bridge

services:
  ors:
    container_name: smartbin-ors
    ports: ["8080:8080"]
    image: openrouteservice/openrouteservice:v6.2.0
    environment:
      - BUILD_GRAPHS=False
      # Forces the container to rebuild the graphs, e.g. when PBF is changed in app.config
      - JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Xms512m -Xmx2000m -XX:MaxMetaspaceSize=2000m
      - CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost
    volumes:
      #PATCH for error "cp: cannot remove '/ors-conf/app.config': Read-only file system"
      - ./ors/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      
      - ./ors/conf:/ors-conf:ro
      #
      - ./logs/:/var/log/ors/
      - ./logs/:/usr/local/tomcat/logs/
      - ./elevation_cache/:/ors-core/data/elevation_cache/
      #- ./graphs.italy:/ors-core/data/graphs
      #
      ## Trentino Alto Adige
      - ./graphs.trentino:/ors-core/data/graphs
      - ./data/trentino-alto-adige.osm.pbf:/ors-core/data/osm_file.pbf
      #
      ## Italia
      #- ./graphs.italy:/ors-core/data/graphs
      #- ./data/italy-latest.osm.pbf:/ors-core/data/osm_file.pbf
      #
      ## Mezzocorona
      #- ./graphs.mezzocorona.restrictions/:/ors-core/data/graphs
      #- ./data/mezzocorona.osm.pbf:/ors-core/data/osm_file.pbf
      #
      ## Povo
      #- ./graphs.povo/:/ors-core/data/graphs
      #- ./data/povo_restrict.osm.pbf:/ors-core/data/osm_file.pbf
      #- ./data/povo.osm.gz:/ors-core/data/osm_file.pbf
      #
#    restart: always

  # #ors-proxy is useful for logging requestes/resposes from vroom to ors 
  # # and allow use of custom restrictions value of profile vehicle
  # # to test restrictions use volume:  ./data/mezzocorona_restrictions.osm.pbf:/ors-core/data/osm_file.pbf 
  ors-proxy:
    container_name: smartbin-ors-proxy
    image: smartbin-ors-proxy:latest
    build:
      context: ./ors-proxy/
    ports: ["9090:9090"]
    environment:
      - ORS_HOST=ors
      - ORS_PORT=8080
    volumes:
      #edits restrictions and restart service to apply
      - ./ors-proxy/config.js:/ors-proxy/config.js:ro
    #restart: always
    depends_on:
      - ors

  vroom: 
    container_name: smartbin-vroom
    image: smartbin-vroom:1.8.0
    build:
      context: ./vroom/
      args:
        VROOM_RELEASE: v1.8.0
        VROOM_EXPRESS_RELEASE: v0.7.0
    ports: ["8081:3000"]
    volumes:
      - ./vroom/conf/config.yml:/vroom-express/config.yml:ro
#    restart: always
    #environment:
    #  - VROOM_LOG=./vroom/conf/
    depends_on:
      - ors

  ors-app:
    container_name: smartbin-ors-app
    image: smartbin-ors-app:latest
    build:
      context: ./ors-app/
      args:
        ORSAPP_RELEASE: v0.6.0
    ports: ["8082:3035"]
    volumes:
      - ./ors-app/build:/ors-app/app/build
      - ./ors-app/Gruntfile.js:/ors-app/Gruntfile.js
    depends_on:
      - ors

  vroom-app:
    container_name: smartbin-vroom-app
    image: smartbin-vroom-app
    build:
      context: ./vroom-app/
      args:
        ORSAPP_RELEASE: v0.4.3
    ports: ["8083:9966"]
    volumes:
      - ./vroom-app/config.js:/vroom-app/src/config/api.js
    depends_on:
      - vroom

  jupyter:
    container_name: smartbin-jupyter
    image: smartbin-jupyter:latest
    build:
      context: ./jupyter/
    ports: ["8084:8888"]
    volumes:
      - ./jupyter/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
      - ./jupyter/data:/home/jovyan/data
      - ./jupyter/test.ipynb:/home/jovyan/test.ipynb
      - ./jupyter/test2.ipynb:/home/jovyan/test2.ipynb
      - ./jupyter/test3.ipynb:/home/jovyan/test3.ipynb
    #restart: always
    depends_on:
      - ors
      #- ors-proxy
      - vroom
    
